# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  apt_packages:
    - libgl1-mesa-dev
    - xvfb
  jobs:
    post_system_dependencies:
      - set -x
      - export DISPLAY=:99.0
      - export PYVISTA_OFF_SCREEN=true
      - which Xvfb
      - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - sleep 30
      - set +x
      - exec "$@"

sphinx:
  configuration: docs/conf.py

python:
  install:
  - method: pip
    path: .
    extra_requirements:
      - docs
