version: "2.1"

jobs:
  docs-build:
    machine:
        image: default
    steps:
      - checkout
      - run:
          name: Setup Python environment
          command: |
            python3 -m venv /home/circleci/eeg_positions_env
            echo "source /home/circleci/eeg_positions_env/bin/activate" >> $BASH_ENV
      - run:
          name: Install Python packages
          command: |
            python -m pip install --upgrade pip
            python -m pip install --editable ".[dev]"
      - run:
          name: Build documentation
          command: |
            make -C docs html
      - store_artifacts:
          path: docs/_build/html/
          destination: dev

workflows:
  commit:
    jobs:
      - docs-build
